= Guided solution (page 2)

1. Open the log file to see a detailed message.

2. Now list the ports for the network associated with the instance and use openstack port list --network <network-name> --long to identify the ports.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack network list
+--------------------------------------+-------------------------+--------------------------------------+
| ID                                   | Name                    | Subnets                              |
+--------------------------------------+-------------------------+--------------------------------------+
| c84e1f23-9d86-47c9-9cd3-851633941dac | scenario-bfx021-network | 671e0166-173e-4c85-a925-dac8546d1bd7 |
| ee961465-e812-4563-aaa8-05adb3476889 | public                  | 3c99909a-9d7a-486a-9df5-6e3fb210df61 |
+--------------------------------------+-------------------------+--------------------------------------+

[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack port list --network scenario-bfx021-network --long
+--------------------------------------+------+-------------------+-------------------------------------------------------------------------------+--------+-----------------+--------------------------+------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                            | Status | Security Groups | Device Owner             | Tags |
+--------------------------------------+------+-------------------+-------------------------------------------------------------------------------+--------+-----------------+--------------------------+------+
| e20c4444-38e4-4ce6-9999-993e1f7882f4 |      | fa:16:3e:12:88:90 | ip_address='192.168.140.1', subnet_id='671e0166-173e-4c85-a925-dac8546d1bd7'  | ACTIVE | None            | network:router_interface |      |
| fcdec0db-bf35-4792-9af6-5feee377efdd |      | fa:16:3e:df:19:9f | ip_address='192.168.140.99', subnet_id='671e0166-173e-4c85-a925-dac8546d1bd7' | ACTIVE | None            | compute:nova             |      |
+--------------------------------------+------+-------------------+-------------------------------------------------------------------------------+--------+-----------------+--------------------------+------+
----


3. List all the ports with device owner and device ID using openstack port list --network <network-name> --long -c id -c device_owner -c device_id.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack port list --network scenario-bfx021-network --long -c id -c device_owner -c device_id
+--------------------------------------+--------------------------+-----------+
| ID                                   | Device Owner             | device_id |
+--------------------------------------+--------------------------+-----------+
| e20c4444-38e4-4ce6-9999-993e1f7882f4 | network:router_interface | None      |
| fcdec0db-bf35-4792-9af6-5feee377efdd | compute:nova             | None      |
+--------------------------------------+--------------------------+-----------+
----
+
- You see that there is no port with device ID as ovn_meta.
+
- This port is missing here.
+
- Each network needs to have this port.
+
- To fix this problem inside the Neutron api container there is a utility called neutron-ovn-db-sync-util which compares neutrons MySQL database with the OVN database and makes sure everything is in sync.
+
- The utility has multiple modes like log, repair, so on.

4. Use OpenShift client to attach to neutron_api POD.
+
----
[student@workstation ~]$ oc rsh -n openstack $(oc get pods -n openstack -l service=neutron -o name)
Defaulted container "neutron-api" out of: neutron-api, neutron-httpd
sh-5.1$
----


5. Within the POD, run neutron-ovn-db-sync-util in log mode.
+
----
neutron-ovn-db-sync-util --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --ovn-neutron_sync_mode log --debug | tee /tmp/neutron-ovn-db-sync-util.log
----


6. Check the toollogs in the POD.
+
----
[neutron@overcloud-controller-0 /]$ less /tmp/neutron-ovn-db-sync-util.log
----


7. You observe that the metadata warning saying Missing metadata port found in Neutron network.
+
----
2025-04-01 12:37:32.879 66 WARNING neutron.plugins.ml2.drivers.ovn.mech_driver.ovsdb.ovn_db_sync [None req-b9d849c8-db41-4acd-8ede-2819c6fb279c - - - - - -] Missing metadata port found in Neutron for network c84e1f23-9d86-47c9-9cd3-851633941dacESC[00m
----


8. Now run the neutron-ovn-db-sync-util command with repair option.
+
----
sh-5.1$ neutron-ovn-db-sync-util --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --ovn-neutron_sync_mode repair --debug  | tee /tmp/neutron-ovn-db-sync-util.log
----


9. Check the logs again and see that now the tool is repairing the missing metadata port: Creating missing metadata port in Neutron and OVN for network.
+
----
2025-04-01 12:38:44.473 75 WARNING neutron.plugins.ml2.drivers.ovn.mech_driver.ovsdb.ovn_db_sync [None req-89b87fc9-c463-4464-87bc-62a221d17e89 - - - - - -] Missing metadata port found in Neutron for network c84e1f23-9d86-47c9-9cd3-851633941dac
2025-04-01 12:38:44.474 75 WARNING neutron.plugins.ml2.drivers.ovn.mech_driver.ovsdb.ovn_db_sync [None req-89b87fc9-c463-4464-87bc-62a221d17e89 - - - - - -] Creating missing metadata port in Neutron and OVN for network c84e1f23-9d86-47c9-9cd3-851633941dac
----


10. Verify the metadata resources those were missing are now available after the DB sync.
+
----
[root@compute02 ~]# ip net
ovnmeta-c84e1f23-9d86-47c9-9cd3-851633941dac (id: 0)
[root@compute02 ~]# podman ps | grep haproxy
3b65c4ae3696  registry.redhat.io/rhoso/openstack-neutron-metadata-agent-ovn-rhel9@sha256:b01c35ee7c7bfb03c91981cbed675628e2a145cb9b0fb123370d4679907736f4  /bin/bash -c exec...  25 seconds ago  Up 25 seconds              neutron-haproxy-ovnmeta-c84e1f23-9d86-47c9-9cd3-851633941dac
----


11. Restart the instance to fetch metadata on boot.
+
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server reboot scenario-bfx021-vm
----
+
[NOTE]
====
If you did not receive any output in the previous step (#20), re-run those commands after the VM has been rebooted.
====


12. Now that the instance has been rebooted, you can establish an SSH connection to it to verify its functionality.
+
----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx021/scenario-bfx021-key.pem cirros@192.168.51.191
$
$ cat /etc/cirros/version
0.5.2
$
----

== Evaluation

As the stack user on the director machine, use the lab command to grade your work. Correct any reported failures and rerun the command until successful.
----
[student@workstation ~]$ lab grade bfx021
----

== Finish

As the student user on the workstation machine, use the lab command to complete this exercise. This step is important to ensure that resources from previous exercises do not impact upcoming exercises.
----
[student@workstation ~]$ lab finish bfx021
----
This concludes this section.

